### ISSUE TITLE
Feature Request: mobile hotspot

### ISSUE THREAD

**Issue by robster7674** [manjaro-pinephone/phosh-dev#25]
It would be great if I could use my PinePhone with Manjaro/PhoSh as a hotspot,  like is described on https://www.cnx-software.com/2021/08/08/how-to-use-pinephone-as-a-mobile-hotspot/.

Is this planned yet? Or is it possible with some workarounds today?

**Comment by alienklown** [comment]
Hello,
I found it in Beta 24:
1. Settings app.
2. Wi-Fi.
3. Vertical ellipses in top right of Wi-Fi settings.
4. " Turn On Wi-Fi Hotspot..." should be the second or middle of three total options.
5. Name your network, set a password, and press blue "Turn On" button in top right of box.

**Comment by robster7674** [comment]
@alienklown :did you get it to work? I can enable the hotspot and I can connect my laptop, but there is no internet connectivity. I verified APN settings and such and those are correct. What am I missing?

**Comment by alienklown** [comment]
So I ran into this problem

PinePhone v1.2b - PINE64<https://wiki.pine64.org/wiki/PinePhone_v1.2b>
PinePhone v1.2b - PINE64<https://wiki.pine64.org/wiki/PinePhone_v1.2b>
The PinePhone v1.2b is a hardware revision of the PinePhone that started shipping in Q4 2020. This page contains information and resources which are specific to the v1.2b revision of the PinePhone.
wiki.pine64.org
Known issues

  *   HDMI hotplug detection is not reliable due to a HW bug in level shifting circuitry for the hot plug detect (HPD) signal between HDMI bridge and A64 SoC.<https://xnux.eu/log/#045>
  *   It is not known if three issues of previous revisions are still present and if yes to which degree, or if they have been fixed by removing resistor R1318, see PinePhone v1.2#Backlight<https://wiki.pine64.org/wiki/PinePhone_v1.2#Backlight> for some details. Please edit this page once this has been confirmed. Mind that there is currently a likely software-related bug present, which also causes the screen to flicker. The bug usually happens after abruptly shutting down the phone previously (for example by forcing it off), in contrast to powering it off.

It didn't used to be a problem for me. I was running another beta. Maybe 11 or 12 and maybe it was postmarketos's phosh shell. Either way until I can actually get mine to dock again I can't troubleshoot your issue directly. However if it doesn't work and acts inconsistent and doesn't give any error messages its likey a power issue of some sort either not enough or a relay like with the HDMI cords and plugs.
I'm gonna start rolling back distros of manjaro beta editions until i find a working one or i might check with a differentmonitor first I'll keep you posted I'm sorry I could'nt be more help yet.
Also if it's not to much of a pain for you might I reccoment trying it from the multi-distro image. I am too.
Also look for compatability stuff like this I've found some but I'm still lookin
this one is oldish i think but PINE64 PinePhone (pine64-pinephone) - postmarketOS<https://wiki.postmarketos.org/wiki/PINE64_PinePhone_(pine64-pinephone)> the working features are to the right its not Manjaro exactly but it gave me the heads up that the one i remeber working probably wasn't postmarketos.
alienklown
PINE64 PinePhone (pine64-pinephone) - postmarketOS<https://wiki.postmarketos.org/wiki/PINE64_PinePhone_(pine64-pinephone)>
Contributors. MartijnBraam; z3ntu; bshah; ollieparanoid (and many more!) Installation. The PinePhone will boot from a bootable microSD card if it is present otherwise it will fall back to booting from internal eMMC.. From a pre-built image (easy method) Official images of postmarketOS for the PinePhone are built at least every week.
wiki.postmarketos.org

________________________________

**Comment by alienklown** [comment]
P.S.
Make sure you have connect the auxiliary 5v power source to the docking bar and:
You may nee one of these:
[See the source image]
A microcontroller. This is the kind I use. It is the Panda Wireless PAU05 and is the only one still capable-when compatible-of twice the Mbps, 300 vs. 150, of all others. I first started using them on the Raspberry Pi and have used them with arduino R3 stuff and it works with the Pinephone (IDK about the pro) and I haven't needed another one yet. It plugs into the USB-C port in the bar and works out of the box. Get a bluetooth fob mouse and keyboard combo so you can use your mouse and keyboard with it. If you use a wired splitter let me know how it works please.
________________________________

**Comment by alienklown** [comment]
and duh sorry, it provides you another, additional access point

________________________________

**Comment by alienklown** [comment]
Dang sorry for the late reply! I'll start checking everyday until you get it going! I had a very similar experience where my internet connectivity was playing games with me so to speak. However before we go looking for the less likely complex issues may I ask have you set up an advanced network configuration for wifi in the Advanced Network Configuration App? If so, then the culprit may be your carrier/service plan needs to be changed to something more directly suited for GSM VOlte modems as was the case with my 1st year of crummy service sold to me by AT&T. I'll start writing legible instructions for you to ensure your advanced network configuration is set correctly; and then before I recommend you purchase another plan I can troubleshoot with you to help us gain an understanding of what's going on based on its behavior. I use lycamobile's GSM29 plan now but that's because they have the best coverage in the southeast; and I can show you how to check/pick that too.
I'll be in touch
________________________________

**Comment by robster7674** [comment]
@alienklown I have not setup an advanced network configuration app. I used the same steps to setup the access point you mentioned in https://github.com/manjaro-pinephone/phosh-dev/issues/25#issuecomment-1179788644. The plan being the issue seems unlikely to me as I have been using it with various iPhones successfully for years. Note that I am not in the US.
